"""Add additional industry info in db

Revision ID: 528183301ff6
Revises: 906b711c75f1
Create Date: 2025-11-19 21:03:13.945929

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '528183301ff6'
down_revision: Union[str, Sequence[str], None] = '906b711c75f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nse_metadata', sa.Column('industry_info', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('nse_metadata', 'industry_info')
    # ### end Alembic commands ###
