"""Add Industry in nse metadata

Revision ID: 906b711c75f1
Revises: f22e3c0aff24
Create Date: 2025-11-17 15:44:19.645735

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '906b711c75f1'
down_revision: Union[str, Sequence[str], None] = 'f22e3c0aff24'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nse_metadata', sa.Column('industry', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('nse_metadata', 'industry')
    # ### end Alembic commands ###
