"""Add refresh date time field for audit and monitoring

Revision ID: 9b360e87d697
Revises: f0f69de9f8d6
Create Date: 2025-11-29 14:25:22.527912

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '9b360e87d697'
down_revision: Union[str, Sequence[str], None] = 'f0f69de9f8d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nse_metadata', sa.Column('refresh_dtm', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('nse_metadata', 'refresh_dtm')
    # ### end Alembic commands ###
