"""Add additional trade details

Revision ID: f0f69de9f8d6
Revises: 528183301ff6
Create Date: 2025-11-29 13:54:14.192762

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'f0f69de9f8d6'
down_revision: Union[str, Sequence[str], None] = '528183301ff6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nse_metadata', sa.Column('total_traded_volume_in_lakhs', sa.Float(), nullable=False))
    op.add_column('nse_metadata', sa.Column('total_traded_value_in_crore', sa.Float(), nullable=False))
    op.add_column('nse_metadata', sa.Column('total_market_cap_in_crore', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('nse_metadata', 'total_market_cap_in_crore')
    op.drop_column('nse_metadata', 'total_traded_value_in_crore')
    op.drop_column('nse_metadata', 'total_traded_volume_in_lakhs')
    # ### end Alembic commands ###
